export const initialCards = [
  {
    id: '0',
    name: 'Директор',
    position: 'Разработчик',
    title: 'Frontend Developer',
    photo: 'https://example.com/photo1.jpg',
    cellId: '1-0',
    parentId: '',
    subordinates: [
      // {
      //   id: '1211',
      //   name: 'Иван',
      //   position: 'Разработчик',
      //   title: 'Frontend Developer',
      //   photo: 'https://example.com/photo1.jpg',
      //   parentId: '',
      //   cellId: '2-1',
      //   subordinates: [
      //     // {
      //     //   id: '1211',
      //     //   name: 'Иван',
      //     //   position: 'Разработчик',
      //     //   title: 'Frontend Developer',
      //     //   photo: 'https://example.com/photo1.jpg',
      //     //   parentId: '',
      //     //   cellId: '0-0',
      //     //   subordinates: [],
      //     // },
      //   ],
      // },
    ],
  },
];

export const cardsList = [
  {
    id: '6',
    name: 'Иван',
    position: 'Разработчик',
    title: 'Frontend Developer',
    photo: 'https://example.com/photo1.jpg',
    parentId: '',
    subordinates: [],
  },
  {
    id: '7',
    name: 'Мария',
    position: 'Дизайнер',
    title: 'UI/UX Designer',
    photo: 'https://example.com/photo2.jpg',
    subordinates: [],
  },
  {
    id: '8',
    name: 'Сергей',
    position: 'Менеджер',
    title: 'Project Manager',
    photo: 'https://example.com/photo3.jpg',
    subordinates: [],
  },
  {
    id: '9',
    name: 'Ольга',
    position: 'Аналитик',
    title: 'Data Analyst',
    photo: 'https://example.com/photo4.jpg',
    subordinates: [],
  },
  {
    id: '10',
    name: 'Алексей Сидоров',
    position: 'Тестировщик',
    title: 'QA Engineer',
    photo: 'https://example.com/photo5.jpg',
    subordinates: [],
  },
  {
    id: '11',
    name: 'Петя',
    position: 'Скорее бы на море',
    title: 'QA Engineer',
    photo: 'https://example.com/photo5.jpg',
    subordinates: [],
  },
  {
    id: '12',
    name: 'Алха',
    position: 'КТо',
    title: 'QA Engineer',
    photo: 'https://example.com/photo5.jpg',
    subordinates: [],
  },
  {
    id: '13',
    name: 'Трампампам',
    position: 'Никто',
    title: 'QA Engineer',
    photo: 'https://example.com/photo5.jpg',
    subordinates: [],
  },
];
