export const initialCards = [
  {
    id: '999',
    position: 'Директор',
    full_name: 'Иванннн',
    department: 'Frontend Developer',
    photo: 'https://example.com/photo1.jpg',
    cellId: '1-0',
    parentId: '',
    subordinates: [
      // {
      //   id: '1211',
      //   name: 'Иван',
      //   position: 'Разработчик',
      //   title: 'Frontend Developer',
      //   photo: 'https://example.com/photo1.jpg',
      //   parentId: '',
      //   cellId: '2-1',
      //   subordinates: [
      //     // {
      //     //   id: '1211',
      //     //   name: 'Иван',
      //     //   position: 'Разработчик',
      //     //   title: 'Frontend Developer',
      //     //   photo: 'https://example.com/photo1.jpg',
      //     //   parentId: '',
      //     //   cellId: '0-0',
      //     //   subordinates: [],
      //     // },
      //   ],
      // },
    ],
  },
];

// export const cardsList = [
//   {
//     id: '6',
//     full_name: 'Иван',
//     position: 'Разработчик',
//     title: 'Frontend Developer',
//     photo: 'https://example.com/photo1.jpg',
//     parentId: '',
//     subordinates: [],
//   },
//   {
//     id: '7',
//     full_name: 'Мария',
//     position: 'Дизайнер',
//     title: 'UI/UX Designer',
//     photo: 'https://example.com/photo2.jpg',
//     subordinates: [],
//   },
//   {
//     id: '8',
//     full_name: 'Сергей',
//     position: 'Менеджер',
//     title: 'Project Manager',
//     photo: 'https://example.com/photo3.jpg',
//     subordinates: [],
//   },
//   {
//     id: '9',
//     full_name: 'Ольга',
//     position: 'Аналитик',
//     title: 'Data Analyst',
//     photo: 'https://example.com/photo4.jpg',
//     subordinates: [],
//   },
//   {
//     id: '10',
//     full_name: 'Алексей Сидоров',
//     position: 'Тестировщик',
//     title: 'QA Engineer',
//     photo: 'https://example.com/photo5.jpg',
//     subordinates: [],
//   },
//   {
//     id: '11',
//     full_name: 'Петя',
//     position: 'Скорее бы на море',
//     title: 'QA Engineer',
//     photo: 'https://example.com/photo5.jpg',
//     subordinates: [],
//   },
//   {
//     id: '12',
//     full_name: 'Алха',
//     position: 'КТо',
//     title: 'QA Engineer',
//     photo: 'https://example.com/photo5.jpg',
//     subordinates: [],
//   },
//   {
//     id: '13',
//     full_name: 'Трампампам',
//     position: 'Никто',
//     title: 'QA Engineer',
//     photo: 'https://example.com/photo5.jpg',
//     subordinates: [],
//   },
// ];
